#!/bin/bash

_install_package(){
    while [[ $# > 0 ]]; do
        if ! type $1 &>/dev/null; then
            if type yum &>/dev/null; then
                yum install -y $1
            elif type apt-get &>/dev/null; then
                apt-get install $1
            elif type brew &>/dev/null; then
                brew install $1
            fi
        fi
        shift
    done
}
_install_package git zsh unzip zip

install_dir=~/.server-scripts

if [[ -d $install_dir ]];then
    rm -rf $install_dir
fi

git clone https://github.com/brivio/scripts.git $install_dir

for i in ~/.bashrc ~/.zshrc
do
    if [[ $(grep $install_dir $i|wc -l) = '0' ]];then
    cat >> $i <<eof
. $install_dir/server-scripts
eof
    fi
done
