#!/bin/bash

yum -y install git zsh unzip zip
install_dir=~/.server-scripts

if [[ -r $install_dir ]];then
    rm -rf $install_dir
fi

git clone https://github.com/brivio/scripts.git $install_dir

for i in ~/.bashrc ~/.zshrc
do
    if [[ $(grep $install_dir $i|wc -l) = '0' ]];then
    cat >> $i <<eof
. $install_dir/server-scripts
eof
done


fi